DROP SCHEMA ROCKINRIO CASCADE;

CREATE SCHEMA ROCKINRIO;
SET SEARCH_PATH TO ROCKINRIO;





CREATE TABLE LOCALIZACAO (
	SIGLA			VARCHAR(6)	NOT NULL,
	DESCRICAO		VARCHAR(30)	NOT NULL,

	PRIMARY KEY (SIGLA)
);




CREATE TABLE IMPRENSA (
	CODIGO			INTEGER		NOT NULL,
	CNPJ			VARCHAR(20)	NOT NULL,
	NOME			VARCHAR(30)	NOT NULL,
	

	PRIMARY KEY (CODIGO)

);	



--atracao(*cod_interno*,nome,h_abertura,h_fechamento,sigla[localizacao])

CREATE TABLE ATRACAO(
	COD_INTERNO		INTEGER		NOT NULL,
	NOME			VARCHAR(24)	NOT NULL,
	H_ABERTURA		VARCHAR(5)	NOT NULL,
	H_FECHAMENTO		VARCHAR(5)	NOT NULL,
	LOCAL_SIGLA		VARCHAR(6)	NOT NULL,
		
	PRIMARY KEY (COD_INTERNO),
	FOREIGN KEY (LOCAL_SIGLA) REFERENCES LOCALIZACAO(SIGLA)

);



CREATE TABLE DIAEVENTO (
	SIGLA 			VARCHAR(6)	NOT NULL,
	DIA_EVENTO		DATE		NOT NULL,
	DIA_SEMANA		VARCHAR(14)	NOT NULL,

	PRIMARY KEY (SIGLA)
);


CREATE TABLE TIPOPATROCINIO (
	NOME			VARCHAR(20)	NOT NULL,
	VALOR			FLOAT		NOT NULL,
	PRIVILEGIOS		VARCHAR(80)	NOT NULL,

	PRIMARY KEY (NOME)
);


CREATE TABLE PATROCINADORES (
	CNPJ			VARCHAR(20)	NOT NULL,
	NOME_FANTASIA		VARCHAR(30)	NOT NULL,
	RAZAO_SOCIAL		VARCHAR(30)	NOT NULL,
	TIPO			VARCHAR(20)	NOT NULL,

	PRIMARY KEY (CNPJ),
	FOREIGN KEY (TIPO) REFERENCES TIPOPATROCINIO(NOME)
);
-- departamento(*numero*,nome,orçamento,nr_funcionarios)

CREATE TABLE DEPARTAMENTO (
	NUM_DEPART		INTEGER		NOT NULL,
	NOME_DEPART		VARCHAR(30)	NOT NULL,
	ORCAMENTO		FLOAT		NOT NULL,
	NR_FUNCIONARIOS		INTEGER			,

	PRIMARY KEY (NUM_DEPART)

);


CREATE TABLE FUNCIONARIO (
	CPF			VARCHAR(15)	NOT NULL,
	RG			VARCHAR(12)	NOT NULL,
	NOME			VARCHAR(50)	NOT NULL,
	DATA_NASC		DATE		NOT NULL,
	ENDERECO		VARCHAR(100)	NOT NULL,
	TELEFONE		VARCHAR(15)	NOT NULL,
	
	PRIMARY KEY (CPF)
);



CREATE TABLE CLIENTE(
	CPF			VARCHAR(15)	NOT NULL,
	RG			VARCHAR(12)	NOT NULL,
	NOME			VARCHAR(50)	NOT NULL,
	ENDERECO		VARCHAR(100)	NOT NULL,
	DATA_NASC		DATE		NOT NULL,
	TELEFONE		VARCHAR(15)	NOT NULL,
	

	PRIMARY KEY (CPF)
);

CREATE TABLE CARTAO (
	CPF			VARCHAR(15)	NOT NULL,
	NUMERO			VARCHAR(16)	NOT NULL,
	NOME_TITULAR		VARCHAR(30)	NOT NULL,
	BANDEIRA		VARCHAR(20)	NOT NULL,
	VALIDADE		VARCHAR(5)	NOT NULL,
	COD_SEGURANCA		INTEGER		NOT NULL,
	
	

	PRIMARY KEY(NUMERO,CPF),
	FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
);


CREATE TABLE TIPOINGRESSO (
	TIPO_ACESSO		VARCHAR(6)	NOT NULL,
	PRECO			FLOAT		NOT NULL,

	PRIMARY KEY (TIPO_ACESSO)
);

CREATE TABLE INGRESSO (
	CODIGO			SERIAL		NOT NULL,
	TIPO_ACESSO		VARCHAR(6)	NOT NULL,

	PRIMARY KEY (CODIGO),
	FOREIGN KEY (TIPO_ACESSO) REFERENCES TIPOINGRESSO(TIPO_ACESSO)
);


-- trabalha(*numero*[departamento],*cpf*[funcionario],funcao)

CREATE TABLE TRABALHA (
	NUMERO			INTEGER		NOT NULL,
	CPF			VARCHAR(15)	NOT NULL,
	FUNCAO			VARCHAR(40)		,
	SALARIO			FLOAT		NOT NULL,
	
	PRIMARY KEY(NUMERO,CPF),
	FOREIGN KEY (NUMERO) REFERENCES DEPARTAMENTO(NUM_DEPART),
	FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF)
);

-- cobre(*cod*[imprensa],*sigla*[localizacao])

CREATE TABLE COBRE (
	COD		INTEGER		NOT NULL,
	SIGLA		VARCHAR(6)	NOT NULL,

	PRIMARY KEY (COD,SIGLA),
	FOREIGN KEY (COD) REFERENCES IMPRENSA(CODIGO),
	FOREIGN KEY (SIGLA) REFERENCES LOCALIZACAO(SIGLA)
);

-- COMPRA(*cpf*[cliente],*sigla*[dia_evento],*cod*[ingresso])

CREATE TABLE COMPRA (
	CPF		VARCHAR(15)		NOT NULL,
	NUMERO_CARTAO   VARCHAR(16)		NOT NULL,
	SIGLA		VARCHAR(6)		NOT NULL,
	COD		INTEGER			NOT NULL,

	PRIMARY KEY(CPF,NUMERO_CARTAO,SIGLA,COD),
	FOREIGN KEY (CPF,NUMERO_CARTAO) REFERENCES CARTAO(CPF,NUMERO),
	FOREIGN KEY (SIGLA) REFERENCES DIAEVENTO(SIGLA),
	FOREIGN KEY (COD) REFERENCES INGRESSO(CODIGO)
);

-- palco(*cod_interno*[atracao],lotacao_max)

CREATE TABLE PALCO(
	COD_INTERNO		INTEGER		NOT NULL,
	LOTACAO_MAX		INTEGER		NOT NULL,

	PRIMARY KEY (COD_INTERNO),
	FOREIGN KEY (COD_INTERNO) REFERENCES ATRACAO(COD_INTERNO)
);

-- restaurante(*cod_interno*[atracao],especialidade,estrelas)

CREATE TABLE RESTAURANTE (
	COD_INTERNO		INTEGER		NOT NULL,
	ESPECIALIDADE		VARCHAR(50)	NOT NULL,
	ESTRELAS		INTEGER		NOT NULL,

	PRIMARY KEY(COD_INTERNO),
	FOREIGN KEY (COD_INTERNO) REFERENCES ATRACAO(COD_INTERNO)

);

-- parque(*cod_interno*[atracao],faixa_etaria,preco)

CREATE TABLE PARQUE(
	COD_INTERNO		INTEGER		NOT NULL,
	FAIXA_ETARIA		VARCHAR(8)		,
	PRECO			FLOAT		NOT NULL,

	PRIMARY KEY(COD_INTERNO),
	FOREIGN KEY (COD_INTERNO) REFERENCES ATRACAO(COD_INTERNO)
);

-- banda(*nome*,descricao_show,cache,cod_interno[palco])



CREATE TABLE BANDA (

	NOME			VARCHAR(50)	NOT NULL,
	DESCRICAO_SHOW		VARCHAR(80)		,
	CACHE_COBRADO		FLOAT		NOT NULL,
	GENERO			VARCHAR(40)	NOT NULL,
	COD_INTERNO		INTEGER		NOT NULL,
	PRIMARY KEY (NOME),
	FOREIGN KEY (COD_INTERNO) REFERENCES PALCO(COD_INTERNO)
);

-- prato(*nome*,preco,cod_interno[restaurante])



CREATE TABLE PRATO (
	NOME			VARCHAR(30)	NOT NULL,
	PRECO			FLOAT		NOT NULL,
	COD_INTERNO		INTEGER		NOT NULL,
	
	PRIMARY KEY (NOME),
	FOREIGN KEY (COD_INTERNO) REFERENCES RESTAURANTE(COD_INTERNO)
);


-- show(*cod_interno*[palco],*nome*[banda],*horario*,sigla[dia_evento])

CREATE TABLE SHOWS (
	NOME			VARCHAR(50)	NOT NULL,
	HORARIO			VARCHAR(5)	NOT NULL,
	SIGLA			VARCHAR(6)	NOT NULL,

	PRIMARY KEY (NOME,HORARIO),
	FOREIGN KEY (NOME) REFERENCES BANDA(NOME),
	FOREIGN KEY (SIGLA) REFERENCES DIAEVENTO(SIGLA)
);


CREATE TABLE CONSOME(
	TICKET			SERIAL,
	CLIENTE			VARCHAR(15)	NOT NULL,
	CARTAO			VARCHAR(16)	NOT NULL,
	PRATO			VARCHAR(30)	NOT NULL,
	QUANTIDADE		INTEGER		NOT NULL,

	PRIMARY KEY (TICKET),
	FOREIGN KEY (CLIENTE,CARTAO) REFERENCES CARTAO(CPF,NUMERO),
	FOREIGN KEY (PRATO) REFERENCES PRATO(NOME)
);

CREATE TABLE LOGIN (
	USUARIO			VARCHAR(15)	NOT NULL,
	SENHA			VARCHAR(20)	NOT NULL,

	PRIMARY KEY (USUARIO),
	FOREIGN KEY (USUARIO) REFERENCES CLIENTE(CPF)
);





